#!/usr/bin/env python3
assert __name__ == '__main__'

# --

import sys

# sys.argv: ['pydra', 'sleep', '1.0']
pydra_args = sys.argv[:2]
mod_args = sys.argv[2:]
while pydra_args[-1].startswith('-'):
    pydra_args.append(mod_args.pop(0))

sys.argv = pydra_args
# Now `'-v' in sys.argv` works properly!

# --

import common
import job_client

import logging
import socket
import subprocess

# --

job_client.LogToWorker.install()

# --

mod_name = sys.argv[-1]
logging.debug('<<mod_name: %s>>', mod_name)
pi = job_client.PydraInterface(mod_name)
ok = pi.shim(*mod_args)
exit(int(not ok))
