#!/usr/bin/env python3
assert __name__ == '__main__'

import common
import job_client
import pydra_mod

import socket
import subprocess
import sys

# --

common.Globals.LOG_FUNC = job_client.log_to_worker

# --

# sys.argv: ['pydra', 'sleep', '1.0']
(_, mod_name, *args) = sys.argv
assert args

# --

common.v_log(3, '<<mod_name: {}>>', mod_name)

mod = pydra_mod.LoadModule(mod_name)
subkeys = mod.pydra_get_subkeys()

def fn_dispatch(subkey, *args):
    assert subkey in subkeys, (subkey, subkeys)
    return job_client.dispatch(mod_name, subkey, mod.pydra_job_client, *args)

ok = mod.pydra_shim(fn_dispatch, *args)
exit(int(not ok))
