#!/usr/bin/env python3
assert __name__ == '__main__'

# --

import sys

# sys.argv: ['pydra', 'sleep', '1.0']
pydra_args = sys.argv[:2]
mod_args = sys.argv[2:]
while pydra_args[-1].startswith('-'):
    pydra_args.append(mod_args.pop(0))

sys.argv = pydra_args
# Now `'-v' in sys.argv` works properly!

# --

import common
import job_client
import pydra_mod

import logging
import socket
import subprocess

# --

job_client.LogToWorker.install()

# --

mod_name = sys.argv[-1]

# --

logging.info('<<mod_name: %s>>', mod_name)

mod = pydra_mod.LoadModule(mod_name)

def fn_dispatch(subkey, *args):
    return job_client.dispatch(mod_name, subkey, mod.pydra_job_client, *args)

ok = mod.pydra_shim(fn_dispatch, *mod_args)
exit(int(not ok))
